name: Grade Submission

on:
  push:
    branches:
      - programming-assignment-*

jobs:
  grade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3 \
            jq \
            g++ \
            iproute2  # includes tc for netem

      - name: Run grading script
        run: |
          sudo python3 grade_github.py
      - name: Show parsed scores in logs
        run: cat parsed_scores.json